trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - script: |
      try {
          ./gradlew.bat clean test aggregate --warning-mode all
          copy target/index.html $(Build.ArtifactStagingDirectory)
      } catch {
          echo 'Ocurrió un error en las pruebas, pero se continuará con la compilación...'
      }
    displayName: 'Ejecutar pruebas y generar informes'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/build/test-results/test/*.xml'
    displayName: 'Publicar resultados de pruebas'

  - script: |
      $timestamp = Get-Date -Format "yyyyMMddHHmm"
      Rename-Item -Path "$(Build.ArtifactStagingDirectory)\target" -NewName "serenity_$timestamp"
    displayName: 'Renombrar carpeta de informes'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'SerenityReports'
    displayName: 'Publicar informes de Serenity BDD'




